### ISSUE TITLE
Stopped to login using Portainer 2.16.0

### ISSUE THREAD

**Issue by mario-tux** [zbejas/portarius#27]
It looks something changed using Portainer 2.16.0. I can't log in with Portarius with this new version. This happens with credentials and token.

**Comment by njohn13** [comment]
+1

**Comment by zbejas** [comment]
Hello.
I think version [1.1.1](https://github.com/zbejas/portarius/releases/tag/1%2C1%2C1) fixed this issue.
This update will also be available on Google tomorrow.
