### ISSUE TITLE
Locked out if the server is missing or unjoignable

### ISSUE THREAD

**Issue by KevoM** [zbejas/portarius#40]
I changed my server, with a new IP. The app retains 'outdated' credentials and only suggest to Try again to connect.

**What is supposed to do?**
If the login fails at launch, it should display authentication again.

**Comment by zbejas** [comment]
You're right, that was a stupid design mistake. Just reset the app data. This is already fixed in the testing version, but it's not yet published.

**Comment by KevoM** [comment]
Thanks ! Yes i cleared the data to get it works
