### ISSUE TITLE
Support for Client Certificates

### ISSUE THREAD

**Issue by Svedrin** [zbejas/portarius#43]
**Is your feature request related to a problem? Please describe.**

I'm using client TLS certificates to secure access to my Portainer instance, so I don't need to worry about the password being brute-forced. This prevents me from using the app, because the app doesn't have support for supplying a client certificate.

**Describe the solution you'd like**

It would be nice if either the App or the OS would prompt me for a certificate like seen [here](https://learn.microsoft.com/en-us/mem/intune/user-help/enroll-android-device-disa-purebred) (search for "prompted to choose"):

![cert prompt](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVWZ5WO6szRddMxvO4wtgCl4qDUfe0a4nnKQ&usqp=CAU)

**Describe alternatives you've considered**

The alternative would be to just allow all access without requiring the certificate, which I would like to avoid for security reasons.

**Additional context**

I found a few pointers on how to implement this, not sure if they help:

* https://stackoverflow.com/questions/35135225/android-webview-handle-onreceivedclientcertrequest
* https://www.codecentric.de/wissens-hub/blog/one-solution-for-android-tlsssl-client-authentication

I'd be happy to test dev versions if it helps.

**Comment by zbejas** [comment]
Try the beta on Google Play, or download it from the link in Discord chat. I haven't really had time to update the Play page, or the Readme regarding that, but SSL verification (or ignoring it rather) is very much added and working as far as I know.
