### ISSUE TITLE
Donation platforms

### ISSUE THREAD

**Issue by aha999** [zbejas/portarius#5]
**Is your feature request related to a problem? Please describe.**

Currently there's no donating information, if users want to show appreciation that way and help fund your time.

**Describe the solution you'd like**

Add a Donations section to the readme and some buttons below as where to donate to your project.

**Describe alternatives you've considered**

Here are some platforms that can be used for donations:
- [OpenCollective](https://opencollective.com/) -- [example](https://opencollective.com/darkreader#sponsor)
- [LiberaPay](https://liberapay.com/) -- [example](https://liberapay.com/k9mail/donate)
- [Github Sponsors](https://github.com/sponsors)
- [PayPal](https://www.paypal.com/)
- [Ko-fi](https://ko-fi.com/)
- [Patreon](https://www.patreon.com/)
- [Flattr](https://flattr.com/)
- [BountySource](https://www.bountysource.com)

Displaying a sponsor button in your repository: [link](https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository) 
A handy list of [donate buttons](https://github.com/aha999/DonateButtons)

**Comment by zbejas** [comment]
Some donation options were added.
