### ISSUE TITLE
 Issue templates

### ISSUE THREAD

**Issue by aha999** [zbejas/portarius#9]
**Is your feature request related to a problem? Please describe.**
Currently, there is no issue templates in this repository, like the one this issue is using with titles for context, which means that issues are not as organized or convenient to understand.

**Describe the solution you'd like**
Implement Issue templates, like this one for example, so users can insert info in pre-determined questions, so they can make better issues. 

Here is a general idea and documentation on how to implement it: [GitHub docs  - issue templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates)

**Describe alternatives you've considered**
This can be done ether as a text-based template, or a sort of a form. I think that the text based version offers more freedom when creating an issue.

**Additional context**
Screenshot example, this is a selection window, that displays after selecting "New Issue" on Github:
![image](https://user-images.githubusercontent.com/50620416/170260260-295bcb14-2dc5-4540-99f7-9054f18cb5c3.png)

**Comment by zbejas** [comment]
Basic issue templates added.
